# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DataVisualisation.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from src.GUI.FileAnalysisWindow import Ui_FileAnalysis
from src.Model.Database import *
class DataVisualisation(object):

    _prop = None


    def setupUi(self, DataVisualisation):
        DataVisualisation.setObjectName("DataVisualisation")
        DataVisualisation.resize(702, 507)
        self.iew_tree_button = QtWidgets.QPushButton(DataVisualisation)
        self.iew_tree_button.setGeometry(QtCore.QRect(240, 390, 201, 25))
        self.iew_tree_button.setObjectName("iew_tree_button")
        self.frame = QtWidgets.QFrame(DataVisualisation)
        self.frame.setGeometry(QtCore.QRect(90, 130, 501, 221))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalFrame = QtWidgets.QFrame(self.frame)
        self.verticalFrame.setGeometry(QtCore.QRect(0, 0, 501, 221))
        self.verticalFrame.setObjectName("verticalFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalFrame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tree_label = QtWidgets.QLabel(self.verticalFrame)
        self.tree_label.setStyleSheet("")
        self.tree_label.setText("")
        self.tree_label.setObjectName("tree_label")
        self.verticalLayout.addWidget(self.tree_label)
        self.frame_2 = QtWidgets.QFrame(DataVisualisation)
        self.frame_2.setGeometry(QtCore.QRect(90, 20, 501, 80))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalFrame = QtWidgets.QFrame(self.frame_2)
        self.horizontalFrame.setGeometry(QtCore.QRect(0, 0, 501, 80))
        self.horizontalFrame.setObjectName("horizontalFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalFrame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.horizontalFrame)
        self.label.setStyleSheet("QLabel{\n"
        "padding:10px;\n"
        "}")
        self.iew_tree_button.clicked.connect(self.viewGeneratedTree)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.horizontalFrame)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        if  not Ui_FileAnalysis().getCompleted(Ui_FileAnalysis):
            self.tree_label.setText("No view at this moment")
            self.tree_label.setStyleSheet('QLabel{'+
            'padding:157px;'+
            'color:gray;}')
        else:
            self.tree_label.setText('Done!!')

        self.retranslateUi(DataVisualisation)
        QtCore.QMetaObject.connectSlotsByName(DataVisualisation)

    def setProp(self,prop=None):
        self._prop = prop
        
    def retranslateUi(self, DataVisualisation):
        _translate = QtCore.QCoreApplication.translate
        DataVisualisation.setWindowTitle(_translate("Form", "Form"))
        self.iew_tree_button.setText(_translate("Form", "View generated tree"))
        self.label.setText(_translate("Form", "File name:"))
    
    def viewGeneratedTree(self):
        if not Ui_FileAnalysis.getCompleted(Ui_FileAnalysis):
            print('Analysis did not complete')

    def runUi(self,DataVisualisation):
        DataVisualisation.show()
        self.database = Database()
        self.file_size = len(self.database.fetchAllFiles())
        if self.file_size == 0:
            self.openNoFileImportedWindow(DataVisualisation)
            
        
    def openNoFileImportedWindow(self,DataVisualisation):
        self.noFileWindow = QtWidgets.QDialog()
        self.noFileLabel = QtWidgets.QLabel("No file exists in database. Please import file first")
        self.accept_button = QtWidgets.QDialogButtonBox.Ok
        self.btn_bx = QtWidgets.QDialogButtonBox(self.accept_button)
        self.noFileWindow.setLayout(QtWidgets.QVBoxLayout())
        self.noFileWindow.layout().addWidget(self.noFileLabel)
        self.noFileWindow.layout().addWidget(self.btn_bx)
        self.callableWindow = lambda:self.closeWindow(DataVisualisation, self.noFileWindow)
        self.btn_bx.accepted.connect(self.callableWindow)
        self.noFileWindow.show()
        
    def closeWindow(self,DataVisualisation,window):
        window.close()
        DataVisualisation.close()

