# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FIleWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog,QDialog
from src.GUI.DialogWindow import *
class Ui_Form(object):
    
    _row = 0
    _col = 0
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(949, 691)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(10, 10, 921, 671))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalFrame = QtWidgets.QFrame(self.frame)
        self.verticalFrame.setGeometry(QtCore.QRect(320, 280, 271, 149))
        self.verticalFrame.setObjectName("verticalFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalFrame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.verticalFrame)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit.setEnabled(False)
        self.verticalLayout.addWidget(self.lineEdit)
        self.pushButton_3 = QtWidgets.QPushButton(self.verticalFrame)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)
        self.horizontalFrame = QtWidgets.QFrame(self.verticalFrame)
        self.horizontalFrame.setObjectName("horizontalFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalFrame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.horizontalFrame)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.horizontalFrame)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.verticalLayout.addWidget(self.horizontalFrame)
        self.horizontalFrame1 = QtWidgets.QFrame(self.frame)
        self.horizontalFrame1.setGeometry(QtCore.QRect(300, 110, 321, 131))
        self.horizontalFrame1.setObjectName("horizontalFrame1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalFrame1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tableWidget = QtWidgets.QTableWidget(self.horizontalFrame1)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.horizontalLayout_2.addWidget(self.tableWidget)
        self.pushButton_3.clicked.connect(self.putTableItem)
        self.pushButton_2.clicked.connect(self.openDialog)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
    
    def openFileDialog(self):
        self.fileName = QFileDialog().getOpenFileName(None,"Open file")
        self.lineEdit.setText(self.fileName[0])
        self.lineEdit.setToolTip("This content cannot be edited")
        return self.fileName
    
    def openDialog(self):
        self.dialog = Ui_Dialog()
        self.dialog.setupUi(windowTitle="Wanring message",labelText="File will be erased. Are you sure you want to proceed ?")
        
    
    def putTableItem(self):
        self.fileContent = self.openFileDialog()
        while self._col <2:
            self.tableWidget.setItem(self._row,self._col,QtWidgets.QTableWidgetItem(self.fileContent[0]))
            self._col+=1
        self._row+=1
    
    

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_3.setText(_translate("Form", "Open file"))
        self.pushButton.setText(_translate("Form", "Import file"))
        self.pushButton_2.setText(_translate("Form", "Cancel"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Recent files"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Date uploaded"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Size"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
