# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FIleWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from QtWidgets import QMainWindow

class Ui_Form(QMainWindow):

    _dialog  = None

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(949, 691)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(10, 10, 921, 671))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(180, 80, 551, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.file_table = QtWidgets.QTableWidget(self.frame)
        self.file_table.setGeometry(QtCore.QRect(290, 130, 311, 441))
        self.file_table.setObjectName("tableWidget")
        self.file_table.setColumnCount(3)
        self.file_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.file_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.file_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.file_table.setHorizontalHeaderItem(2, item)
        self.lineEdit.setEnabled(False)
        self.pushButton.setStyleSheet('color:green')
        self.pushButton_2.setStyleSheet('color:red')
        self.openFileButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.openFileButton.setText("Open file")
        self.openFileButton.clicked.connect(self.openFile)
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        self.pushButton_2.clicked.connect(self.closeWindow)
        self.pushButton.clicked.connect(self.writeElementToTable)
    
    def writeElementToTable(self):
        self.file_t 

    def closeWindow(self,Form):
        Form.close()
            
    
    def openFile(self):
        self._dialog = QtWidgets.QFileDialog()
        self.file_name = QtWidgets.QFileDialog.getOpenFileName(self._dialog,"Open file")
        self.lineEdit.setText(self.file_name[0])

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "Import file"))
        self.pushButton_2.setText(_translate("Form", "Cancel"))
        item = self.file_table.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Recent files"))
        item = self.file_table.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Date uploaded"))
        item = self.file_table.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Size"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
