# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SettingsWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from src.Model.User import *
from src.Model.Database import *
class Ui_Settings(object):
    def setupUi(self, Settings):
        Settings.setObjectName("Settings")
        Settings.resize(729, 527)
        self.account_label = QtWidgets.QLabel(Settings)
        self.account_label.setGeometry(QtCore.QRect(60, 30, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.account_label.setFont(font)
        self.account_label.setObjectName("account_label")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Settings)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(60, 100, 601, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.display_name_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.display_name_label.setObjectName("display_name_label")
        self.horizontalLayout.addWidget(self.display_name_label)
        self.full_name_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.full_name_label.setObjectName("full_name_label")
        self.horizontalLayout.addWidget(self.full_name_label)
        self.phone_number_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.phone_number_label.setObjectName("phone_number_label")
        self.horizontalLayout.addWidget(self.phone_number_label)
        self.email_address_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.email_address_label.setObjectName("email_address_label")
        self.horizontalLayout.addWidget(self.email_address_label)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Settings)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(60, 150, 601, 80))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.display_name_text = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.display_name_text.setObjectName("display_name_text")
        self.horizontalLayout_2.addWidget(self.display_name_text)
        self.full_name_text = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.full_name_text.setObjectName("full_name_text")
        self.horizontalLayout_2.addWidget(self.full_name_text)
        self.phone_number_text = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.phone_number_text.setObjectName("phone_number_text")
        self.horizontalLayout_2.addWidget(self.phone_number_text)
        self.email_address_text = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.email_address_text.setObjectName("email_address_text")
        self.horizontalLayout_2.addWidget(self.email_address_text)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(Settings)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(60, 300, 611, 71))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.delete_account_info_label = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.delete_account_info_label.setObjectName("delete_account_info_label")
        self.horizontalLayout_3.addWidget(self.delete_account_info_label)
        self.label_6 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        self.delete_account_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.delete_account_button.setObjectName("delete_account_button")
        self.horizontalLayout_3.addWidget(self.delete_account_button)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.delete_account_label = QtWidgets.QLabel(Settings)
        self.delete_account_label.setGeometry(QtCore.QRect(60, 270, 111, 17))
        self.delete_account_label.setObjectName("delete_account_label")
        self.display_name_text.setEnabled(False)
        self.full_name_text.setEnabled(False)
        self.phone_number_text.setEnabled(False)
        self.email_address_text.setEnabled(False)
        # self.delete_account_button.clicked.connect(self.deleteAccount)
        self.retranslateUi(Settings)
        QtCore.QMetaObject.connectSlotsByName(Settings)

        

    def retranslateUi(self, Settings):
        _translate = QtCore.QCoreApplication.translate
        Settings.setWindowTitle(_translate("Form", "Settings"))       
        self.phone_number_label.setText(_translate("Form", "Phone number"))
        self.email_address_label.setText(_translate("Form", "Email address"))
        self.delete_account_info_label.setText(_translate("Form", "This action will delete all of your personal information. Are you sure? "))
        self.delete_account_button.setText(_translate("Form", "Delete anyway"))
        self.delete_account_label.setText(_translate("Form", "Delete account"))
    
    def runUi(self,Settings):
        Settings.show()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Settings = QtWidgets.QWidget()
    ui = Ui_Settings()
    ui.setupUi(Settings)
    Settings.show()
    sys.exit(app.exec_())
