# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_Folder/TreeWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Tree(QtWidgets.QWidget):

    def setupUi(self):
        self.setObjectName("TreeWindow")
        self.setFixedSize(900, 650)
        self.verticalFrame = QtWidgets.QFrame(self)
        self.verticalFrame.setGeometry(QtCore.QRect(40, 60, 800, 600))
        self.verticalFrame.setObjectName("verticalFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalFrame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tree_label = QtWidgets.QLabel(self.verticalFrame)
        self.verticalFrame.move(90,10)
        self.tree_label.move(325,10)
        self.tree_label.setText("")
        self.tree_label.setObjectName("tree_label")
        self.verticalLayout.addWidget(self.tree_label)
        self.tree_icon = QtGui.QPixmap("dot_tree.png")
        self.tree_label.setPixmap(self.tree_icon)
        self.setStyleSheet("*{background-color:#fff0f5;}")

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("TreeWindow", "Decision Tree Window"))
    
    def runUi(self):
        self.show()
