# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(981, 591)
        self.horizontalFrame = QtWidgets.QFrame(Form)
        self.horizontalFrame.setGeometry(QtCore.QRect(80, 30, 811, 80))
        self.horizontalFrame.setObjectName("horizontalFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalFrame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.user_icon = QtWidgets.QLabel(self.horizontalFrame)
        self.user_icon.setStyleSheet("\n"
"image: url(:/image-header/Downloads/icons8-user-30.png);\n"
"\n"
"QLabel hover user_menu{\n"
"background-color:red\n"
"\n"
"\n"
"}")
        self.user_icon.setText("")
        self.user_icon.setObjectName("user_icon")
        self.horizontalLayout.addWidget(self.user_icon)
        self.home_button = QtWidgets.QPushButton(self.horizontalFrame)
        self.home_button.setObjectName("home_button")
        self.horizontalLayout.addWidget(self.home_button)
        self.file_button = QtWidgets.QPushButton(self.horizontalFrame)
        self.file_button.setObjectName("file_button")
        self.horizontalLayout.addWidget(self.file_button)
        self.data_analysis_button = QtWidgets.QPushButton(self.horizontalFrame)
        self.data_analysis_button.setObjectName("data_analysis_button")
        self.horizontalLayout.addWidget(self.data_analysis_button)
        self.data_vis_button = QtWidgets.QPushButton(self.horizontalFrame)
        self.data_vis_button.setObjectName("data_vis_button")
        self.horizontalLayout.addWidget(self.data_vis_button)
        self.about_button = QtWidgets.QPushButton(self.horizontalFrame)
        self.about_button.setObjectName("about_button")
        self.horizontalLayout.addWidget(self.about_button)
        self.user_menu = QtWidgets.QFrame(Form)
        self.user_menu.setGeometry(QtCore.QRect(80, 110, 160, 361))
        self.user_menu.setStyleSheet("QFrame {\n"
"opacity:0px;\n"
"}\n"
"\n"
"")
        self.user_menu.setObjectName("user_menu")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.user_menu)
        self.verticalLayout.setObjectName("verticalLayout")
        self.account_button = QtWidgets.QPushButton(self.user_menu)
        self.account_button.setObjectName("account_button")
        self.verticalLayout.addWidget(self.account_button)
        self.settings_button = QtWidgets.QPushButton(self.user_menu)
        self.settings_button.setObjectName("settings_button")
        self.verticalLayout.addWidget(self.settings_button)
        self.log_out_button = QtWidgets.QPushButton(self.user_menu)
        self.log_out_button.setObjectName("log_out_button")
        self.verticalLayout.addWidget(self.log_out_button)
        self.FileFrame = QtWidgets.QFrame(Form)
        self.FileFrame.setGeometry(QtCore.QRect(280, 110, 621, 351))
        self.FileFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.FileFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.FileFrame.setObjectName("FileFrame")
        self.fileButtonsFrame = QtWidgets.QFrame(self.FileFrame)
        self.fileButtonsFrame.setGeometry(QtCore.QRect(100, 300, 431, 41))
        self.fileButtonsFrame.setObjectName("fileButtonsFrame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.fileButtonsFrame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.filePathEdit = QtWidgets.QLineEdit(self.fileButtonsFrame)
        self.filePathEdit.setObjectName("filePathEdit")
        self.horizontalLayout_2.addWidget(self.filePathEdit)
        self.fileOpenButton = QtWidgets.QPushButton(self.fileButtonsFrame)
        self.fileOpenButton.setObjectName("fileOpenButton")
        self.horizontalLayout_2.addWidget(self.fileOpenButton)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.home_button.setText(_translate("Form", "Home"))
        self.file_button.setText(_translate("Form", "FIles"))
        self.data_analysis_button.setText(_translate("Form", "Data analysis"))
        self.data_vis_button.setText(_translate("Form", "Data visualization"))
        self.about_button.setText(_translate("Form", "About"))
        self.account_button.setText(_translate("Form", "Account"))
        self.settings_button.setText(_translate("Form", "Settings"))
        self.log_out_button.setText(_translate("Form", "Log out"))
        self.fileOpenButton.setText(_translate("Form", "..."))
