# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SettingsWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from src.Model.Database import *

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(729, 527)
        self.account_label = QtWidgets.QLabel(Form)
        self.account_label.setGeometry(QtCore.QRect(60, 30, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.account_label.setFont(font)
        self.account_label.setObjectName("account_label")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(60, 100, 601, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.display_name_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.display_name_label.setObjectName("display_name_label")
        self.horizontalLayout.addWidget(self.display_name_label)
        self.full_name_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.full_name_label.setObjectName("full_name_label")
        self.horizontalLayout.addWidget(self.full_name_label)
        self.phone_number_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.phone_number_label.setObjectName("phone_number_label")
        self.horizontalLayout.addWidget(self.phone_number_label)
        self.email_address_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.email_address_label.setObjectName("email_address_label")
        self.horizontalLayout.addWidget(self.email_address_label)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(60, 150, 601, 80))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.display_name_text = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.display_name_text.setObjectName("display_name_text")
        self.horizontalLayout_2.addWidget(self.display_name_text)
        self.full_name_text = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.full_name_text.setObjectName("full_name_text")
        self.horizontalLayout_2.addWidget(self.full_name_text)
        self.phone_number_text = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.phone_number_text.setObjectName("phone_number_text")
        self.horizontalLayout_2.addWidget(self.phone_number_text)
        self.email_address_text = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.email_address_text.setObjectName("email_address_text")
        self.horizontalLayout_2.addWidget(self.email_address_text)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(60, 300, 611, 71))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.delete_account_info_label = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.delete_account_info_label.setObjectName("delete_account_info_label")
        self.horizontalLayout_3.addWidget(self.delete_account_info_label)
        self.label_6 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        self.delete_account_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.delete_account_button.setObjectName("delete_account_button")
        self.horizontalLayout_3.addWidget(self.delete_account_button)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.delete_account_label = QtWidgets.QLabel(Form)
        self.delete_account_label.setGeometry(QtCore.QRect(60, 270, 111, 17))
        self.delete_account_label.setObjectName("delete_account_label")
        self.delete_account_button.clicked.connect(self.deleteAccount)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(230, 410, 251, 80))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.save_changes_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.save_changes_button.setObjectName("save_changes_button")
        self.horizontalLayout_4.addWidget(self.save_changes_button)
        self.cancel_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.cancel_button.setObjectName("cancel_button")
        self.horizontalLayout_4.addWidget(self.cancel_button)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def deleteAccount(self,user):
        self.database = Database()
        self.flag = 0
        try:
            if not self.database.establishConnection(user):
                raise Exception('Could not connect to database')
            self.user_data = self.database.fetchAllUsers()
            for data in self.user_data:
                if data[0] == user.getUserId():
                    self.flag =1
                    self.deletion_query = "delete from user where user_name= ? and active_account = true"
                    try:
                        if not self.database.runRandomQuery(self.deletion_query):
                            raise Exception('Error during query execution')
                            return
                        print("Account was sucessfully deleted")
                    except Exception as e:
                        print(e)
                return
            if not self.flag == 1:
                print("User is not currently active or credentials are wrong")
            
                        #Place code to warn user that this account was deleted
                    


        except Exception as e:
            print(e)

        
    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.account_label.setText(_translate("Form", "Account "))
        self.display_name_label.setText(_translate("Form", "Display name"))
        self.full_name_label.setText(_translate("Form", "Full name"))
        self.phone_number_label.setText(_translate("Form", "Phone number"))
        self.email_address_label.setText(_translate("Form", "Email address"))
        self.delete_account_info_label.setText(_translate("Form", "This action will delete all of your personal information. Are you sure? "))
        self.delete_account_button.setText(_translate("Form", "Delete anyway"))
        self.delete_account_label.setText(_translate("Form", "Delete account"))
        self.save_changes_button.setText(_translate("Form", "Save changes"))
        self.cancel_button.setText(_translate("Form", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
